#!/usr/bin/env bash
# Build the production .env for the slink box from SSM + the RDS endpoint
# (roadmap task 33). Run on the operator host (has the slink AWS creds); pipe to
# a file, then scp to the box:  bash build-env.sh > .env.prod
#
# Kept out of the box's own IAM scope on purpose (Safety Rule #0 — no instance
# profile / IAM changes on the shared account); secrets are resolved here.
set -euo pipefail
export AWS_PROFILE="${AWS_PROFILE:-slink}"
REGION="${AWS_REGION:-us-east-1}"

ssm() { aws ssm get-parameter --name "$1" --with-decryption --query Parameter.Value --output text --region "$REGION"; }

DB_PW="$(ssm /slink/prod/db_password)"
JWT="$(ssm /slink/prod/jwt_secret)"
COOKIE="$(ssm /slink/prod/cookie_secret)"
REVAL="$(ssm /slink/prod/revalidate_secret)"

RDS_HOST="$(aws rds describe-db-instances --db-instance-identifier slink-db \
  --query 'DBInstances[0].Endpoint.Address' --output text --region "$REGION")"

DATABASE_URL="postgres://saludlink:${DB_PW}@${RDS_HOST}:5432/medusa"

# Publishable key: set as a repo variable once prod is seeded; placeholder keeps
# the first medusa-only bring-up unblocked.
PUBKEY="${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY:-pk_replace_after_seed}"

cat <<ENV
# Generated by build-env.sh — do NOT commit. Contains prod secrets.
NODE_ENV=production

# --- Medusa ---
DATABASE_URL=${DATABASE_URL}
REDIS_URL=redis://redis:6379
JWT_SECRET=${JWT}
COOKIE_SECRET=${COOKIE}
STORE_CORS=https://saludlinkusa.com,https://www.saludlinkusa.com
ADMIN_CORS=https://manage.saludlinkusa.com
AUTH_CORS=https://saludlinkusa.com,https://www.saludlinkusa.com,https://manage.saludlinkusa.com
MEDUSA_BACKEND_URL=https://manage.saludlinkusa.com

# --- Storefront (server runtime; NEXT_PUBLIC_* also baked at image build) ---
NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${PUBKEY}
MEDUSA_BACKEND_URL=https://manage.saludlinkusa.com
NEXT_PUBLIC_BASE_URL=https://saludlinkusa.com
NEXT_PUBLIC_DEFAULT_REGION=us
REVALIDATE_SECRET=${REVAL}
COMING_SOON=true
PREVIEW_CODE=900800

# --- Edge ---
ACME_EMAIL=ops@saludlinkusa.com
ENV
